#pragma once

#include "AvailableDataTypesRequest.h"
#include "CurrentTimeRequest.h"
#include "GetDataRequest.h"
#include "GetSitesRequest.h"
#include "HelloWorldRequest.h"
#include "MachineInformationRequest.h"
#include "SiteInformationRequest.h"
#include "AddStatePeriodRequest.h"
#include "GetStatePeriodsRequest.h"
#include "AlarmActivationsRequest.h"
#include "CurrentAlarmStateRequest.h"
#include "AlarmSettingsRequest.h"
#include "GetAlarmLevelHistory.h"
#include "GetDataTimes.h"
#include "TypeInformationRequest.h"
#include "ChannelInformationRequest.h"